#!/bin/bash
srcdir=/home/scf-27/melesse/cs402/warmup1
# srcdir=/home/vagrant/Documents/usc/cs402/warmup1
# /bin/rm -rf grading_$$
# mkdir grading_$$
# cd grading_$$
# cp ../my402list.c .
# cp $srcdir/cs402.h .
# cp $srcdir/my402list.h .
# cp $srcdir/listtest.c .
# cp $srcdir/Makefile .
# make

# seeds=( 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 )

# #
# # for the following commands, each correct behavior gets 2 point
# # gets 2 points if "./listtest" command produces NOTHING
# # gets 0 point if "./listtest" command produces ANY output
# #
# for f in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
# do
# echo "===> test_$f"
# ./listtest -seed=$seeds[$f]
# done

# # Clean up temporary directory
# #
# /bin/rm -rf grading_$$
# exit 0


# set srcdir=~csci570b/public/cs402/warmup1
srcdir=/home/scf-27/melesse/cs402/warmup1/testfilesOriginal

#
# (B1)
# for the following commands, each case is worth 2 points
# gets 2 points if "diff" command produces NOTHING
# gets 1 point if "diff" command produces SOME output showing
#     very minor formatting errors (i.e., extra or missing space/tab/cr characters)
# gets 0 point if "diff" command produce SOME output showing
#     incorrect information in the output
#
/bin/rm -f f?.sort f??.sort
for f in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14
do
echo "===> $srcdir/f$f"
./warmup1 sort $srcdir/f$f > f$f.sort
diff $srcdir/f$f.sort f$f.sort
done
/bin/rm -f f?.sort f??.sort

#
# (B2)
# for the following commands, each case is worth 2 points
# gets 2 points if "diff" command produces NOTHING
# gets 1 point if "diff" command produces SOME output showing
#     only invisible formatting errors
# gets 0 point if "diff" command produce SOME output showing
#     incorrect information in the output
#
/bin/rm -f f??.sort
for f in 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
do
echo "===> $srcdir/f$f"
cat $srcdir/f$f | ./warmup1 sort > f$f.sort
diff $srcdir/f$f.sort f$f.sort
done
/bin/rm -f f??.sort