#!/bin/bash
# srcdir=/home/scf-27/melesse/cs402/warmup1
srcdir=/home/vagrant/Documents/usc/cs402/warmup1
/bin/rm -rf grading_$$
mkdir grading_$$
cd grading_$$
cp ../my402list.c .
cp $srcdir/cs402.h .
cp $srcdir/my402list.h .
cp $srcdir/listtest.c .
cp $srcdir/Makefile .
make

seeds=( 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 )

#
# for the following commands, each correct behavior gets 2 point
# gets 2 points if "./listtest" command produces NOTHING
# gets 0 point if "./listtest" command produces ANY output
#
for f in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
do
echo "===> test_$f"
./listtest -seed=$seeds[$f]
done

# Clean up temporary directory
#
/bin/rm -rf grading_$$
exit 0
